// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<frc::SpeedController> RobotMap::driveBaseSubFrontLeftSC;
std::shared_ptr<frc::SpeedController> RobotMap::driveBaseSubFrontRightSC;
std::shared_ptr<frc::SpeedController> RobotMap::driveBaseSubBackLeftSC;
std::shared_ptr<frc::SpeedController> RobotMap::driveBaseSubBackRightSC;
std::shared_ptr<frc::RobotDrive> RobotMap::driveBaseSubRobotDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driveBaseSubFrontLeftSC.reset(new frc::Spark(1));
    lw->AddActuator("DriveBaseSub", "FrontLeftSC", std::static_pointer_cast<frc::Spark>(driveBaseSubFrontLeftSC));
    
    driveBaseSubFrontRightSC.reset(new frc::Spark(2));
    lw->AddActuator("DriveBaseSub", "FrontRightSC", std::static_pointer_cast<frc::Spark>(driveBaseSubFrontRightSC));
    
    driveBaseSubBackLeftSC.reset(new frc::Spark(3));
    lw->AddActuator("DriveBaseSub", "BackLeftSC", std::static_pointer_cast<frc::Spark>(driveBaseSubBackLeftSC));
    
    driveBaseSubBackRightSC.reset(new frc::Spark(4));
    lw->AddActuator("DriveBaseSub", "BackRightSC", std::static_pointer_cast<frc::Spark>(driveBaseSubBackRightSC));
    
    driveBaseSubRobotDrive.reset(new frc::RobotDrive(driveBaseSubFrontLeftSC, driveBaseSubBackLeftSC,
              driveBaseSubFrontRightSC, driveBaseSubBackRightSC));
    
    driveBaseSubRobotDrive->SetSafetyEnabled(false);
        driveBaseSubRobotDrive->SetExpiration(0.1);
        driveBaseSubRobotDrive->SetSensitivity(0.5);
        driveBaseSubRobotDrive->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
